# Generated by Django 5.2.4 on 2025-08-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('powerup', 'Power-Up'), ('arma', 'Arma'), ('moneda', 'Moneda'), ('vida', 'Vida Extra'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('rareza', models.IntegerField(default=1)),
                ('efecto', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('activo_en_juego', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
