# Generated by Django 5.2.4 on 2025-08-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminventario',
            options={'ordering': ['-rareza', 'nombre'], 'verbose_name': 'Ítem de Inventario', 'verbose_name_plural': 'Ítems de Inventario'},
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='nivel_minimo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='tiempo_duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='tipo',
            field=models.CharField(choices=[('powerup', 'Power-Up'), ('arma', 'Arma'), ('moneda', 'Moneda'), ('vida', 'Vida Extra'), ('consumible', 'Consumible'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
